/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, useTexture} from "@react-three/drei";
import React from "react";

export function Office(props) {
  const { section } = props;
  const { nodes, materials } = useGLTF("models/scene.gltf");


  return (
    <group {...props} dispose={null}>
      <group name="Plant" position={[1.523, 0.41, -1.271]} scale={[2.358, 2.363, 2.55]}>
        <group name="Pot_Plant" position={[-0.001, -0.009, -0.002]} rotation={[0.02, 0, 0]} scale={100}>
          <mesh name="Pot_Plant_1" geometry={nodes.Pot_Plant_1.geometry} material={materials.mat24} />
          <mesh name="Pot_Plant_2" geometry={nodes.Pot_Plant_2.geometry} material={materials.mat19} />
          <mesh name="Pot_Plant_3" geometry={nodes.Pot_Plant_3.geometry} material={materials['mat21.002']} />
          <mesh name="Pot_Plant_4" geometry={nodes.Pot_Plant_4.geometry} material={materials['mat9.002']} />
          <mesh name="Pot_Plant_5" geometry={nodes.Pot_Plant_5.geometry} material={materials['mat20.004']} />
        </group>
      </group>
      <group name="CokeBottle" position={[0.847, 0.634, -1.119]} rotation={[0, 0, -Math.PI]} scale={[-0.024, -0.017, -0.029]}>
        <group name="Bottle" position={[-0.439, 15.14, -5.074]} rotation={[-Math.PI / 2, 0, 0]} scale={[237.553, 189.858, 743.778]}>
          <mesh name="Bottle_1" geometry={nodes.Bottle_1.geometry} material={materials['Material.001']} />
          <mesh name="Bottle_2" geometry={nodes.Bottle_2.geometry} material={materials.plastic} />
          <mesh name="Bottle_3" geometry={nodes.Bottle_3.geometry} material={materials['Material.002']} />
          <mesh name="Bottle_4" geometry={nodes.Bottle_4.geometry} material={materials.Drank} />
        </group>
      </group>
      <group name="Books" position={[-1.461, 0.657, -1.111]} scale={[1.25, 1.202, 1.146]}>
        <mesh name="Books001" geometry={nodes.Books001.geometry} material={materials['Material.003']} position={[-0.017, -0.014, 0.003]} scale={100} />
      </group>
      <group name="Lamp" position={[-1.268, 0.986, -1.29]} scale={[1.593, 1.197, 1.768]}>
        <mesh name="Lamp_with_shade" geometry={nodes.Lamp_with_shade.geometry} material={materials['Material.004']} position={[-0.013, -0.014, 0.002]} scale={100} />
      </group>
      <group name="Chair" position={[0.25, 0.5, 0]} rotation={[-Math.PI, 0.054, -Math.PI]} scale={[0.752, 0.679, 0.625]}>
        <mesh name="ExecutiveChair1" geometry={nodes.ExecutiveChair1.geometry} material={materials.LeatherExecutiveChair1} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
      <group name="Dumbell1" position={[-1.135, 0.278, -1.276]} rotation={[0, 1.549, 0]}>
        <mesh name="Dumbbell" geometry={nodes.Dumbbell.geometry} material={materials['Material.005']} position={[0.001, -0.033, -0.045]} scale={100} />
      </group>
      <group name="Dumbell2" position={[-0.949, 0.278, -1.292]} rotation={[0, 1.549, 0]}>
        <mesh name="Dumbbell001" geometry={nodes.Dumbbell001.geometry} material={materials['Material.006']} position={[0.001, -0.033, -0.045]} scale={100} />
      </group>
      <group name="Cacti" position={[-1.779, 1.039, 0.65]} rotation={[0, 0.575, 0]}>
        <mesh name="Node-Mesh" geometry={nodes['Node-Mesh'].geometry} material={materials.mat9} />
        <mesh name="Node-Mesh_1" geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat14} />
        <mesh name="Node-Mesh_2" geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat21} />
        <mesh name="Node-Mesh_3" geometry={nodes['Node-Mesh_3'].geometry} material={materials.mat20} />
        <mesh name="Node-Mesh_4" geometry={nodes['Node-Mesh_4'].geometry} material={materials.mat16} />
        <mesh name="Node-Mesh_5" geometry={nodes['Node-Mesh_5'].geometry} material={materials.mat10} />
        <mesh name="Node-Mesh_6" geometry={nodes['Node-Mesh_6'].geometry} material={materials.mat13} />
        <mesh name="Node-Mesh_7" geometry={nodes['Node-Mesh_7'].geometry} material={materials.mat17} />
        <mesh name="Node-Mesh_8" geometry={nodes['Node-Mesh_8'].geometry} material={materials.mat15} />
      </group>
      <mesh name="Unit" geometry={nodes.Unit.geometry} material={materials.wood} position={[-0.845, 0.208, -1.082]} rotation={[0, -1.568, 0]} scale={[2.561, 2.009, 3.614]} />
      <group name="MessageBoard" position={[-1.5, 1.153, 1.547]} rotation={[0, -0.007, -Math.PI]} scale={[-0.027, -0.01, -0.007]}>
        <mesh name="Message_Board_1" geometry={nodes.Message_Board_1.geometry} material={materials.Mat} />
        <mesh name="Message_Board_1_1" geometry={nodes.Message_Board_1_1.geometry} material={materials['Material.012']} />
      </group>
      <mesh name="Kettlebell" geometry={nodes.Kettlebell.geometry} material={materials.phong1SG} position={[-1.376, 0.376, -1.21]} />
      <group name="Picture" position={[0.199, 1.839, -1.594]} rotation={[0, 0, 0.004]} scale={[1.88, 1, 1]}>
        <mesh name="Node-Mesh002" geometry={nodes['Node-Mesh002'].geometry} material={materials.mat23} />
        <mesh name="Node-Mesh002_1" geometry={nodes['Node-Mesh002_1'].geometry} material={materials['mat21.003']} />
        <mesh name="Node-Mesh002_2" geometry={nodes['Node-Mesh002_2'].geometry} material={materials['mat15.002']} />
        <mesh name="Node-Mesh002_3" geometry={nodes['Node-Mesh002_3'].geometry} material={materials['mat24.002']} />
        <mesh name="Node-Mesh002_4" geometry={nodes['Node-Mesh002_4'].geometry} material={materials['mat25.001']} />
        <mesh name="Node-Mesh002_5" geometry={nodes['Node-Mesh002_5'].geometry} material={materials.Material} />
      </group>
      <group name="Desk" position={[0.372, 1.082, -1.1]} rotation={[1.554, -0.011, 0.005]} scale={[0.375, 1, 0.203]}>
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.011']} />
        <mesh name="Plane003_1" geometry={nodes.Plane003_1.geometry} material={materials['mat20.001']} />
        <mesh name="Plane003_2" geometry={nodes.Plane003_2.geometry} material={materials['mat23.002']} />
        <mesh name="Plane003_3" geometry={nodes.Plane003_3.geometry} material={materials['mat22.003']} />
        <mesh name="Plane003_4" geometry={nodes.Plane003_4.geometry} material={materials['mat17.001']} />
        <mesh name="Plane003_5" geometry={nodes.Plane003_5.geometry} material={materials.mat8} />
        <mesh name="Plane003_6" geometry={nodes.Plane003_6.geometry} material={materials['Material.007']} />
      </group>
      <group name="rugRectangle" position={[-0.799, 0.172, 1.851]} rotation={[3.141, -0.003, 3.14]} scale={[1.396, 1.945, 1.773]}>
        <mesh name="rugRectangle_2" geometry={nodes.rugRectangle_2.geometry} material={materials.carpet} />
        <mesh name="rugRectangle_2_1" geometry={nodes.rugRectangle_2_1.geometry} material={materials.carpetDarker} />
      </group>
      <group name="Structure" position={[0, 0, 0.01]} scale={[2.005, 1, 2.005]}>
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.Floor} />
        <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials.Default} />
        <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials.Walls} />
        <mesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={materials.Outer} />
      </group>
    </group>
  );
}

useGLTF.preload("models/scene.gltf");

